import React, { Children } from 'react';
import Head from 'next/head';
import { ChakraProvider } from '@chakra-ui/react';
import { Inter } from 'next/font/google'
import { Carousel } from 'antd';

const inter = Inter({ subsets: ['latin'] })

const contentStyle: React.CSSProperties = {
  height: '460px',
  color: '#fff',
  lineHeight: '160px',
  textAlign: 'center',
  background: '#364d79',
  };

export default function Home() {
  return (
    <>
      <Head>
        <title>Business App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className=" ">

          <Carousel autoplay>
            <div>
              <h3 style={contentStyle}>1</h3>
            </div>
            <div>
              <h3 style={contentStyle}>2</h3>
            </div>
            <div>
              <h3 style={contentStyle}>3</h3>
            </div>
            <div>
              <h3 style={contentStyle}>4</h3>
            </div>
          </Carousel>

          <div>

          </div>

      </main>
      
    </>
  )
}
